### ISSUE TITLE
unquit discord

### ISSUE THREAD

**Issue by danik4985** [Ali00035/Ali00035#2]
why did you quit :(((((((((((((((((((((

**Comment by danik4985** [comment]
@Ali00035

**Comment by FartCheese** [comment]
> @Ali00035

he is inactive

**Comment by sigmaclientwastaken** [comment]
> > @Ali00035
> 
> he is inactive and he says he wont be on discord anymore (cuz its a shitty place)

I agree, discord is hell, reddit is worse don't go there

**Comment by BobIsMyManager** [comment]
> > @Ali00035
> 
> he is inactive and he says he wont be on discord anymore (cuz its a shitty place)

I think we can all agree on that, thats why personally avoid using it when possible

**Comment by FartCheese** [comment]
> > > @Ali00035
> > 
> > 
> > he is inactive and he says he wont be on discord anymore (cuz its a shitty place)
> 
> I agree, discord is hell, reddit is worse don't go there



> > > @Ali00035
> > 
> > 
> > he is inactive and he says he wont be on discord anymore (cuz its a shitty place)
> 
> I think we can all agree on that, thats why personally avoid using it when possible

thats why i dont use it

**Comment by ChungusHook** [comment]
idk, i understand why people would dislike discord... really depends on how you use it but if you feel like its not good for you i get why you would quit.

**Comment by FartCheese** [comment]
> idk, i understand why people would dislike discord... really depends on how you use it but if you feel like its not good for you i get why you would quit.

^^

**Comment by FartCheese** [comment]
also he said that hes gonna be inactive on CCBlueX forums and guilded

**Comment by BobIsMyManager** [comment]
so basically gone everywhere

**Comment by FartCheese** [comment]
> so basically gone everywhere

FireLX partying in the background rn

**Comment by Ali00035** [comment]
ok stop this, fine, ill unquit discord.
